export const FONTS = {
  regular: "Poppins-Regular",
  medium: "Poppins-Medium",
  semiBold: "Poppins-SemiBold",
  bold:"Poppins-Bold",
  MontMedium:"Montserrat-Medium",
  MontRegular:"Montserrat-Regular",
   MontSemiBold:"Montserrat-SemiBold",
   MontBold:"Montserrat-Bold",
   MontExtraBold:"Montserrat-ExtraBold",
   Interbold:"Inter_18pt-Bold",
   InterRegular:"Inter_18pt-Regular",
   InterMedium:"Inter_18pt-Medium",
   InterSemiBold:"Inter_18pt-SemiBold",
   MetropolicRegular:"Metropolis-Regular",
   MetropolicMedium:"Metropolis-Medium",
   MetropolicBold:"Metropolis-Bold",
   MetropolicSemibold:"Metropolis-SemiBold",
   sfprobold:"sfpro-bold",
   sfprosemibold:"sfpro-semibold",
   sfproMedium:"sfpro-medium",
   sfproBlack:"sfpro-black",
   sfproRegular:"sfpro-regular",

};